### ISSUE TITLE
NormalizeColorSchemes

### ISSUE THREAD

**Issue by shafcodes** [hanweny/DMOL#2]
@hanweny Please normalize the color scheme and intensity for all varibles across the correlation matrices. The intensity of the color should reflect the strength of correlation consistently across all the correlation matrices regardless of the week and construct. That way, they look comparable across the constructs. You can also layout the correlation matrices better by assigning them to a fixed grid based on the len of the constructs per week for a quick side-by-side comparison.

**Comment by hanweny** [comment]
The color scheme is now consistent across week and construct
