### ISSUE TITLE
DescriptionsOfFoldersInReadMe

### ISSUE THREAD

**Issue by shafcodes** [hanweny/DMOL#4]
@Fanbo1 
Please include the descriptions for each of the folders in the DMOL repo to explain what is included in each folder. You can reach out to @hanweny and @calebpitts to ask them what each of those folders contain and then edit the Read Me file.

**Comment by Fanbo1** [comment]
Hi, Shaf

Sorry for the late response. I just saw it right now.

**Comment by shafcodes** [comment]
That's quite alright @Fanbo1. I see you are on the right track. Make sure to take assistance from Caleb and Henry as needed. tty soon.

**Comment by Fanbo1** [comment]
@shafcodes 
with the help from Caleb and Henry, I have finished the descriptions. Please let me know if there is anything need to change.
